[Android] Add all Activities and xml to act all of func
nnstreamer/nnstreamer-example pull request #217
Opened 2020-10-02 16:09 UTC by Joojihwan

[Edit] NNStreamerActivity : Add connection of views with layout and Edit onClick to act each buttons
[Add] PreviewActivity, activity_preview.xml : Get bitmap Image from NNStreamerActivity and Show the Image. Can save or retry.
[Add] SettingActivity, activity_setting.xml : Set the conditions to send to NNStreamerActivity with spinner, editText

Every layout is not landscape.
Can open own gallery with NNStreamerActvitiy's button
Can capture the surfaceView with countdown
Can save the captured image in PreviewActivity in 'autocapture' folder

Signed-off-by: Joojihwan <wngustnf@naver.com>

2020-10-02 16:16 UTC, park-sang-hyun commented on android/example_app/nnstreamer-ssd-autocapture/AndroidManifest.xml
> +            android:screenOrientation="portrait"> <!-- Change Orientation from landscape to portrait-->
```suggestion
            android:screenOrientation="portrait">
```

2020-10-02 16:22 UTC, park-sang-hyun requested changes
I'd like to remove the comment.

2020-10-02 16:22 UTC, park-sang-hyun commented on android/example_app/nnstreamer-ssd-autocapture/AndroidManifest.xml
> +            android:screenOrientation="portrait"> <!-- Change Orientation from landscape to portrait-->
I'd like to remove the comment.

2020-10-02 16:29 UTC, Joojihwan commented on android/example_app/nnstreamer-ssd-autocapture/AndroidManifest.xml
> +            android:screenOrientation="portrait">
Occured a problem about sign-off

2020-10-02 23:56 UTC, macaron10 commented
LGTM

2020-10-03 02:22 UTC, Soyeong-k-1230 commented
LGTM

2020-10-03 04:25 UTC, park-sang-hyun commented
LGTM!

2020-10-03 06:50 UTC, JeongYeonUk commented
LGTM

2020-10-03 08:01 UTC, gichan-jang commented on android/example_app/nnstreamer-ssd-autocapture/res/layout/activity_preview.xml
> +</LinearLayout>
Add new line here.

2020-10-03 08:02 UTC, gichan-jang commented on android/example_app/nnstreamer-ssd-autocapture/res/layout/activity_preview.xml
> +</LinearLayout>
Check other files also.

2020-10-03 21:23 UTC, zhoonit commented
Please keep newline changes in one commit either with `git rebase -i` the fix commit or `git reset --soft HEAD~1 && git commit --amend` and do `git push -f`

2020-10-04 08:23 UTC, anyj0527 approved these changes
LGTM

2020-10-04 08:25 UTC, merged