[Tizen/Web] Refactoring ImageClassificationOffloading example
nnstreamer/nnstreamer-example pull request #339
Opened 2024-06-07 08:21 UTC by niley7464

- Create utility module
- Functionalization of duplicated part
- Remove unused variables
- Change var variables to use let type
- Declare variables closer to where they are used

2024-06-10 01:24 UTC, yeonykim2 requested changes

2024-06-10 01:24 UTC, yeonykim2 commented on Tizen.web/ImageClassificationOffloading/js/main.js
> +async function runOffloading() {
The `ip` is not set in `runOffloading()` func. So, it can be removed `async`.

2024-06-10 05:48 UTC, niley7464 commented on Tizen.web/ImageClassificationOffloading/js/main.js
> +async function runOffloading() {
I missed that part during the refactoring process.
Thank you :)

2024-06-10 08:22 UTC, myungjoo approved these changes

2024-06-11 14:30 UTC, wooksong approved these changes

2024-06-11 14:32 UTC, wooksong commented on Tizen.web/ImageClassificationOffloading/js/utils.js
> +    return maxIdx;
```suggestion
    let max = array[0];
    let maxIdx = 0;

    for (let i = 0; i < array.length; ++i) {
        if (array[i] > max) {
            maxIdx = i;
            max = array[i];
        }
    }
    return maxIdx;
```

2024-06-11 14:33 UTC, wooksong commented on Tizen.web/ImageClassificationOffloading/js/utils.js
> +    return maxIdx;
```suggestion
    let maxIdx = array.indexOf(Math.max(...array));

    return maxIdx;
```

2024-06-11 14:33 UTC, wooksong commented on Tizen.web/ImageClassificationOffloading/js/utils.js
> +    var imgsrc = GetImgPath.count++ % MAX_IMG_CNT;
```suggestion
    let imgsrc = GetImgPath.count++ % MAX_IMG_CNT;
```

2024-06-11 14:33 UTC, wooksong commented on Tizen.web/ImageClassificationOffloading/js/utils.js
> +    var labelList = fHandle.readString();
```suggestion
    const fHandle = tizen.filesystem.openFile('wgt-package/res/labels.txt', 'r');
    const labelList = fHandle.readString();
```

2024-06-12 01:24 UTC, niley7464 commented on Tizen.web/ImageClassificationOffloading/js/utils.js
> +    return maxIdx;
I divided the modules and forgot to change util.js 😅
Thank you :)

2024-06-12 01:25 UTC, niley7464 commented on Tizen.web/ImageClassificationOffloading/js/utils.js
> +    var imgsrc = GetImgPath.count++ % MAX_IMG_CNT;
Updated! Thank you

2024-06-12 01:25 UTC, niley7464 commented on Tizen.web/ImageClassificationOffloading/js/utils.js
> +    var labelList = fHandle.readString();
Updated! Thank you

2024-06-12 02:09 UTC, myungjoo commented on Tizen.web/ImageClassificationOffloading/js/utils.js
> +/* SPDX-License-Identifier: Apache-2.0-only */
```s/SPDX-License-Identifier: Apache-2.0-only/SPDX-License-Identifier: Apache-2.0/```

2024-06-12 02:10 UTC, myungjoo reviewed
Update SPDX identifiers.

There is no "Apache-2.0-only". Use "Apache-2.0".
LGPL-2.0-only has some context...

2024-06-12 02:15 UTC, niley7464 commented on Tizen.web/ImageClassificationOffloading/js/utils.js
> +/* SPDX-License-Identifier: Apache-2.0-only */
Updated! Thank you :)

2024-06-12 03:54 UTC, merged